import Axios from 'axios'

export default {
  /**
   * Post article image file to server
   * @param formData image file and userId
   * @returns Promise
   */
  uploadImageByFile: (formData: FormData) => {
    return Axios({
      method: 'POST',
      url: '/articles/images',
      data: formData,
      headers: { 'Access-Control-Allow-Origin': '*' }
    })
  },
  /**
   * Post article to server
   *
   * @param articleBody JSON data generated by editorjs
   * @param project Id of associated project
   * @param owner Id of article creator
   * @returns Promise
   */
  create: (articleBody: any, project: string, owner: string, isPublished: boolean) => {
    return Axios({
      method: 'POST',
      url: '/articles',
      data: {
        body: articleBody,
        project,
        owner,
        isPublished
      }
    })
  },
  /**
   * Update an article
   *
   * @param article Article
   * @returns Promise
   */
  update: (article: any) => {
    return Axios({
      method: 'PATCH',
      url: `/articles/${article.id}`,
      data: article
    })
  },
  /**
   * Get an article
   * @returns Promise
   */
  get: async (id: string) => {
    const response = await Axios({
      method: 'GET',
      url: '/articles/' + id
    })
    return response.data
  },
  /**
   * Search articles by search term
   * @param searchTerm term to search by
   * @returns Promise
   */
  search: async (searchTerm: string) => {
    const response = await Axios({
      method: 'POST',
      url: '/articles/search',
      data: {
        searchTerm
      }
    })
    return response.data
  },
  /**
   * Delete article
   * @param articleId
   * @returns Promise
   */
  deleteArticle: (articleId: string) => {
    return Axios({
      method: 'DELETE',
      url: `/articles/${articleId}`
    })
  }
}
