// Auth
export const ACHECKAUTH = 'CHECKAUTH'
export const ALOGIN = 'LOGIN'
export const AREGISTER = 'REGISTER'
export const AREFRESHTOKENS = 'AREFRESHTOKENS'

export const AGETAUTHENTICATEDUSER = 'GETAUTHENTICATEDUSER'

export const ALOADCONSTANTS = 'LOADCONSTANTS'

// Habitats
export const ALOADHABITATS = 'ALOADHABITATS'
export const ALOADCURRENTHABITAT = 'ALOADCURRENTHABITAT'

// Notifications
export const FETCH_NOTIFICATION = 'FETCH_NOTIFICATION'
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS'
export const GET_NEW_NOTIFICATIONS_COUNT = 'GET_NEW_NOTIFICATIONS_COUNT'

// Roomplans
export const AROOMPLANS = {
  CREATE: 'AROOMPLANSCREATE',
  SAVE: 'AROOMPLANSSAVE',
  DELETE: 'AROOMPLANSDELETE'
}
