// App constants
export const CONSTANTSADD = 'CONSTANTSADD'

// Auth
export const LOGIN = 'LOGIN'
export const SETTOKENS = 'SETTOKENS'
export const SETUSER = 'SETUSER'
export const LOGOUT = 'LOGOUT'

// User Settings
export const AUTHUSERUPDATE = 'AUTHUSERUPDATE'

// Users
export const USERSADD = 'USERSADD'
export const USERSUPDATE = 'USERSUPDATE'
export const USERSDELETE = 'USERSDELETE'
export const USERADD = 'USERADD'
export const USERUPDATE = 'USERUPDATE'

// Habitats
export const HABITATSADD = 'HABITATSADD'
export const HABITATSUPDATE = 'HABITATSUPDATE'
export const HABITATSDELETE = 'HABITATSDELETE'
export const CURRENTHABITATADD = 'CURRENTHABITATADD'
export const CURRENTHABITATUPDATE = 'CURRENTHABITATUPDATE'
export const INVITETOKENADD = 'INVITETOKENADD'
export const INVITETOKENCLEAR = 'INVITETOKENCLEAR'
export const HANDLEHABITATMODAL = 'HANDLEHABITATMODAL'

// Room plans
export const ROOMPLANSADD = 'ROOMPLANSADD'
export const ROOMPLANSUPDATE = 'ROOMPLANSUPDATE'
export const ROOMPLANSDELETE = 'ROOMPLANSDELETE'
export const ROOMPLANADD = 'ROOMPLANADD'
export const ROOMPLANUPDATE = 'ROOMPLANUPDATE'
export const ROOMPLANDELETE = 'ROOMPLANDELETE'

// Notifications
export const NOTIFICATIONSADD = 'NOTIFICATIONSADD'
export const NOTIFICATIONADD = 'NOTIFICATIONADD'
export const NEW_NOTIFICATIONS_COUNT_ADD = 'NEW_NOTIFICATIONS_COUNT_ADD'

export const ROOMPLAN = {
  DIMENSIONUNITS: {
    SET: 'DIMENSIONUNITSSET'
  },
  CURSOR: 'ROOMPLANCURSOR',
  CURSORS: {
    DEFAULT: 'ROOMPLANCURSORDEFAULT',
    POINTER: 'ROOMPLANCURSORPOINTER',
    GRAB: 'ROOMPLANCURSORGRAB',
    GRABBING: 'ROOMPLANCURSORGRABBING'
  },
  STAGECONFIG: {
    SET: 'ROOMPLANSTAGECONFIGSET'
  },
  SELECT: {
    TOGGLE: 'ROOMPLANTOGGLESELECT'
  },
  DRAWING: {
    TOGGLE: 'ROOMPLANTOGGLEDRAWING'
  },
  HISTORY: {
    UNDO: 'ROOMPLANUNDO',
    REDO: 'ROOMPLANREDO',
    SAVE: 'ROOMPLANSAVE'
  },
  ELEMENTS: {
    ADD: 'ROOMPLANELEMENTSADD',
    DELETE: 'ROOMPLANELEMENTSDELETE',
    UPDATE: 'ROOMPLANELEMENTSUPDATE',
    SELECT: 'ROOMPLANELEMENTSSELECT',
    SNAP: 'ROOMPLANELEMENTSSNAP'
  },
  DOORS: {
    ADD: 'ROOMPLANDOORSADD',
    DELETE: 'ROOMPLANDOORSDELETE'
  },
  WALLS: {
    ADD: 'ROOMPLANWALLADD',
    UPDATE: 'ROOMPLANWALLUPDATE',
    DELETE: 'ROOMPLANWALLDELETE'
  },
  WALLSEGMENT: {
    ADD: 'ROOMPLANWALLSEGMENTADD',
    UPDATE: 'ROOMPLANWALLSEGMENTUPDATE',
    DELETE: 'ROOMPLANWALLSEGMENTDELETE'
  },
  CATALOGUE: {
    ADD: 'CATALOGUEADD',
    UPDATE: 'CATALOGUEUPDATE',
    DELETE: 'CATALOGUEDELETE'
  }
}
